#!/usr/bin/env node
// dsh-plugins-all/scripts/aggregate.cjs
//
// 生成 dsh-plugins-all 的 bundle patch（cordis.patch.yml）：把本仓库各插件
// 自己的 insert 块搬进同一份 patch，profile 侧因此只需要登记一个 bundle。
//
// 为什么是"投影"而不是手抄行定义：
//   每个插件既要能独立安装，也要能被本聚合包收录，同一个名册行必须两处同源。
//   生成器逐行搬运子插件 patch 里的 insert 块（只剥注释与空行，不解析 YAML
//   语义），因此 id / name / config 之类的字段不会在搬运中丢失或被改写。
//
// 用法：
//   node scripts/aggregate.cjs           生成 cordis.patch.yml
//   node scripts/aggregate.cjs --check   只校验：磁盘内容与生成结果一致则退出 0
//
// 退出码：0 = 已写入 / 一致；1 = 清单有问题 或 --check 发现不一致。

'use strict';

const fs = require('fs');
const path = require('path');

const PKG_DIR = path.resolve(__dirname, '..');
const REPO_ROOT = path.dirname(PKG_DIR);
const MANIFEST = path.join(PKG_DIR, 'aggregate.json');
const OUTPUT = path.join(PKG_DIR, 'cordis.patch.yml');

const HEADER = [
  '# AUTO-GENERATED by scripts/aggregate.cjs — do not edit',
  '#',
  '# 本文件是 dsh-plugins-all 的 bundle patch：把各插件的名册行一次性插入 web',
  '# profile。profile 侧只需要在 dsh.profile.bundles 里登记 dsh-plugins-all 一个',
  '# 条目，各插件自己的包名不必再单独列入 bundles。',
  '#',
  '# 真源：',
  '#   aggregate.json                  收录哪些插件',
  '#   ../<插件目录>/cordis.patch.yml  每一行 id / name / config 的定义',
  '# 改完跑：npm run build:patch',
  '#',
  '# 约束：被本包收录的插件应当从 dsh.profile.bundles 里移除，两边不要同时登记。',
  '# 名册里出现两次、且两次行 id **不同**时，client 侧会把它算成两个来源并直接抛',
  '#   client-modules: package <包名> resolves from multiple active Loader sources',
  '# 行 id **相同**的重复插入会被 loader 按 id 合并成一条，不报错。',
  '# 另：插件管理页的「已安装」分组按 profile dependencies 列举、按 bundles 判定',
  '# 启用状态，所以被收录的成员会显示为「已关闭」——那是包级标签，不代表它的行没跑。',
  '# 成员的单插件启停请用 profile cordis.patch.yml 的 id 定向覆盖。',
  '',
].join('\n');

/** 读取并解析 aggregate.json。 */
function readManifest() {
  let parsed;
  try {
    parsed = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  } catch (err) {
    fail(`无法解析 ${path.relative(REPO_ROOT, MANIFEST)}：${err.message}`);
  }
  const members = parsed.members;
  if (!Array.isArray(members) || members.length === 0) fail('aggregate.json 的 members 必须是非空数组');
  return members;
}

/** 读一个 JSON 文件；失败时以清单条目为上下文报错。 */
function readJson(file, what) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (err) {
    fail(`无法读取 ${what}（${path.relative(REPO_ROOT, file)}）：${err.message}`);
  }
}

/**
 * 剥掉注释行与空行后返回子插件 patch 的正文。
 * 只做行级过滤，不做 YAML 解析——字段原样保留，缩进不变。
 */
function patchBlock(text, label) {
  const kept = [];
  for (const line of text.split(/\r?\n/)) {
    if (/^\s*#/.test(line)) continue; // 整行注释
    if (line.trim() === '') continue; // 空行
    kept.push(line);
  }
  if (kept.length === 0) fail(`${label} 的 cordis.patch.yml 去掉注释后是空的`);

  const topLevel = kept.filter((line) => /^-[ \t]/.test(line));
  if (topLevel.length !== 1 || !/^-[ \t]+insert:[ \t]*$/.test(topLevel[0])) {
    fail(
      `${label} 的 cordis.patch.yml 必须只含一个顶层 "- insert:" 块` +
        `（实际顶层条目 ${topLevel.length} 个）；多个块或 id 覆盖请先拆分`
    );
  }
  return kept;
}

/**
 * 从 insert 块里取出行 id 与包名，并做形状校验。
 * 只认"第一个 - id: 行 + 紧随其后缩进更深的第一个 name: 行"这一对，
 * 不去匹配 config 内部可能出现的同名键。
 */
function rowIdentity(block, label) {
  let idIndent = -1;
  let id = null;
  let name = null;
  for (const line of block) {
    const indent = line.match(/^[ \t]*/)[0].length;
    if (id === null) {
      const m = line.match(/^[ \t]*-[ \t]+id:[ \t]*(\S+)[ \t]*$/);
      if (m) {
        id = m[1];
        idIndent = indent;
      }
      continue;
    }
    if (name === null) {
      const m = line.match(/^[ \t]*name:[ \t]*(\S+)[ \t]*$/);
      if (m) {
        if (indent <= idIndent) fail(`${label} 的 name 行缩进不深于 id 行，insert 块形状异常`);
        name = m[1];
      }
      continue;
    }
    if (indent <= idIndent && /^[ \t]*-[ \t]/.test(line)) {
      fail(`${label} 的 insert 块含第二个列表项：${line.trim()}（本包要求一行一包，请拆成两个成员）`);
    }
  }
  if (id === null) fail(`${label} 的 insert 块缺 "- id:"`);
  if (name === null) fail(`${label} 的 insert 块缺 "name:"`);
  return { id, name };
}

/** 在 name 行之后插入 disabled: true，缩进与 name 行对齐。 */
function withDisabled(block, label) {
  const out = [];
  let done = false;
  for (const line of block) {
    out.push(line);
    if (!done && /^[ \t]*name:[ \t]*\S+[ \t]*$/.test(line)) {
      const indent = line.match(/^[ \t]*/)[0];
      out.push(`${indent}disabled: true`);
      done = true;
    }
  }
  if (!done) fail(`${label} 的 insert 块找不到 name 行，无法写入 disabled`);
  return out;
}

/** 把 manifest 的一个条目投影成一段生成文本。 */
function memberSection(member, seen) {
  if (typeof member.dir !== 'string' || member.dir === '') fail('aggregate.json 的成员缺 dir');
  const dir = path.join(REPO_ROOT, member.dir);
  if (!fs.existsSync(path.join(dir, 'package.json'))) fail(`成员目录不存在或缺 package.json：${member.dir}`);

  const pkg = readJson(path.join(dir, 'package.json'), `成员 ${member.dir} 的 package.json`);
  const label = pkg.name || member.dir;
  const patchRel = pkg.dsh && pkg.dsh.bundle && pkg.dsh.bundle.patch;
  if (typeof patchRel !== 'string') fail(`${label} 的 package.json 未声明 dsh.bundle.patch`);

  const patchFile = path.join(dir, patchRel);
  if (!fs.existsSync(patchFile)) fail(`${label} 的 dsh.bundle.patch 指向的文件不存在：${patchRel}`);

  let block = patchBlock(fs.readFileSync(patchFile, 'utf8'), label);
  if (member.disabled === true) block = withDisabled(block, label);

  const row = rowIdentity(block, label);
  if (row.name !== pkg.name) {
    fail(`${label} 的 insert 行 name (${row.name}) 与它的 package.json name (${pkg.name}) 不一致`);
  }
  if (seen.ids.has(row.id)) fail(`行 id 重复：${row.id}（被 ${seen.ids.get(row.id)} 与 ${label} 同时使用）`);
  if (seen.names.has(row.name)) fail(`包名重复：${row.name}（被 ${seen.names.get(row.name)} 与 ${label} 同时使用）`);
  seen.ids.set(row.id, label);
  seen.names.set(row.name, label);

  const comment = typeof member.note === 'string' && member.note !== ''
    ? `# ---- ${label} —— ${member.note}`
    : `# ---- ${label}`;
  return `${comment}\n${block.join('\n')}\n`;
}

/** 组装完整输出文本（LF、无 BOM、末尾单个换行）。 */
function render() {
  const members = readManifest();
  const seen = { ids: new Map(), names: new Map() };
  const sections = members.map((member) => memberSection(member, seen));
  return `${HEADER}\n${sections.join('\n')}`;
}

function fail(message) {
  console.error(`[aggregate] ${message}`);
  process.exit(1);
}

function main() {
  const check = process.argv.slice(2).includes('--check');
  const next = render();
  const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : null;

  if (check) {
    if (current === next) {
      console.log(`[aggregate] OK  ${path.relative(REPO_ROOT, OUTPUT)} 与清单一致`);
      process.exit(0);
    }
    console.error(`[aggregate] 不一致：${path.relative(REPO_ROOT, OUTPUT)} 需要重新生成`);
    console.error('[aggregate] 跑一遍 npm run build:patch 后重新提交');
    process.exit(1);
  }

  if (current === next) {
    console.log(`[aggregate] 无变化  ${path.relative(REPO_ROOT, OUTPUT)}`);
    process.exit(0);
  }
  fs.writeFileSync(OUTPUT, next, 'utf8');
  console.log(`[aggregate] 已写入 ${path.relative(REPO_ROOT, OUTPUT)}（${next.split('\n').length - 1} 行）`);
}

main();
